image: python:latest

pages:
  variables:
    PYTHONPATH: "."
  script:
    - mkdir public
    - cd python
    - pip install -r requirements.txt
    - python -m eurec4a.compile ../metadata > ../public/meta.yaml
    - python -m eurec4a.compile ../metadata -j > ../public/meta.json
    - python -m eurec4a.generate_reports -m ../metadata -o ../public/
  artifacts:
    paths:
      - public
  only:
    - master
